### ISSUE TITLE
Problem: Loading time for meteor mongo data is extremely slow

### ISSUE THREAD

**Issue by ioioio8888** [Blockrazor/gitbloq#34]
Problem: Loading time for meteor data is extremely slow, It takes a lot of time(few minutes) to get the mongo data.

**Comment by samuelralak** [comment]
how many requests are we making when the application boots up?

**Comment by ioioio8888** [comment]
> how many requests are we making when the application boots up?

It subscribed to 4 mongo collections when it boots up.

**Comment by ioioio8888** [comment]
solved by reducing the number of doc to be returned at once
